name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    env:
      VERSION: 0.0.0
      NUGET_API_SOURCE: https://api.nuget.org/v3/index.json

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: |
        dotnet restore

    - name: Pack
      run: |
        dotnet pack \
          --no-restore \
          --configuration Release \
          -p:PackageVersion=${{ env.VERSION }}-alpha${{ github.run_number }} \
          GetStanza

    - name: Publish
      env:
        NUGET_GETSTANZA_PUSH_API_KEY: ${{ secrets.NUGET_GETSTANZA_PUSH_API_KEY }}
      run: |
        dotnet nuget push \
          ./GetStanza/bin/Release/GetStanza.${{ env.VERSION }}-alpha${{ github.run_number }}.nupkg \
          --api-key ${{ env.NUGET_GETSTANZA_PUSH_API_KEY }} \
          --source "${{ env.NUGET_API_SOURCE }}"